# -*- coding: utf-8 -*-
"""load_explore_tables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/alxogm/HIGI2022/blob/main/python/load_explore_tables.ipynb
"""

import os
import requests
import pandas as pd
import matplotlib.pyplot as plt

"""**En este cuaderno se muestran algunos ejemplos de como descargar archivos con tablas directamente desde el cuaderno. Así como la manipuclación con la libreria pandas**"""

url = 'https://www.indexmundi.com/map/?t=0&v=25&r=xx&1=en'
html = requests.get(url).content
Birth_rate = pd.read_html(html)
Birth_rate=Birth_rate[1]

Birth_rate.head()

Birth_rate.keys()

Birth_rate.describe()

Birth_rate[Birth_rate['Birth rate (births/1,000 population)']>19]

from urllib import request

url = 'https://smn.conagua.gob.mx/tools/RESOURCES/com_archivo_datos_resumenes/202201010000Lluv.csv'
request.urlretrieve(url, "2022101010000Lluv.csv")

data_2021=pd.read_csv("/content/2021101010000Lluv.csv", encoding = 'ISO-8859-1')
data_2022=pd.read_csv("/content/2022101010000Lluv.csv", encoding = 'ISO-8859-1')

data_2022

data_2021.keys()

data_2021['ene-21'].hist()

data_2021.plot(kind="scatter", x="LON", y="LAT",alpha=0.1)

# c is the attribute we'll map onto colors, s is the attribute we'll represent with circle size.
data_2021.plot(kind="scatter", x="LON", y="LAT",c='ene-21', label="ene-21", cmap=plt.get_cmap("jet"),
    colorbar=True, alpha=0.4, figsize=(10,7),
)
plt.legend()
plt.show()

data_2021_2022=pd.merge(data_2021,data_2022,on=["LON","LAT","EDO","CLAVE","ESTACION"],how="outer")

data_2021_2022

# c is the attribute we'll map onto colors, s is the attribute we'll represent with circle size.
for i in range(1,3):
  data_2021_2022.plot(kind="scatter", x="LON", y="LAT",c=f"ene-2{i}", label=f"ene-2{i}", cmap=plt.get_cmap("jet"),
    colorbar=True, alpha=0.4, figsize=(10,7),
)
  plt.legend()
  plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %pip install tabula-py
import tabula

lluvias= tabula.io.read_pdf("https://smn.conagua.gob.mx/tools/DATA/Climatolog%C3%ADa/Pronóstico%20climático/Temperatura%20y%20Lluvia/PREC/2021.pdf", pages='all')
lluvias=lluvias[0]

lluvias.head()

df.describe()

lluvias.hist()

"""Ejercicio: Mira los tutoriales https://pandas.pydata.org/docs/getting_started/index.html y realiza los ejemplos usando las tablas que tenemos, u otras de elección. """