# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rDGrGB5ELCJg5ueiZp1uX0beCzGRop6V
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import math as math
from scipy.optimize import minimize
from scipy import stats
data=np.load("line.npy")
x=data[0]
y=data[1]
yerr=data[2]

plt.errorbar(x,y,yerr,fmt='.')
plt.plot(x,a_op*x+b_op)

def chi2(params):
  a=params[0]
  b=params[1]
  ymodel=a*x+b
  chi2=0.5*np.sum((y-ymodel)**2/yerr**2)
  return chi2

res= minimize(chi2, x0=[-0,0], options={'disp':True})
a_op,b_op=res.x
print(a_op,b_op)

